# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-17 23:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='create_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 17, 23, 49, 46, 83702)),
        ),
        migrations.AlterField(
            model_name='downvote',
            name='create_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 17, 23, 49, 46, 86254)),
        ),
        migrations.AlterField(
            model_name='question',
            name='create_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 17, 23, 49, 46, 84287)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='create_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 17, 23, 49, 46, 83195)),
        ),
        migrations.AlterField(
            model_name='upvote',
            name='create_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 17, 23, 49, 46, 85676)),
        ),
    ]
